version: "3.9"
services:
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - vulder-school-form-db:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
volumes:
  vulder-school-form-db:
    external: true
